### ISSUE TITLE
Cluster Status:HEALTH_WARN

### ISSUE THREAD

**Issue by wzs803** [Crapworks/ceph-dash#54] opened 2017-09-11 12:55 UTC
操作系统:cenots7.3 x64
ceph版本:ceph version 12.2.0  luminous (rc)
ceph-dash-luminous: 
ceph -s 状态：health: HEALTH_OK
但是python ceph-dash.py 访问http://ip:5000 
Ceph Cluster Overall Status： Cluster Status:HEALTH_WARN

**Comment by Crapworks** [comment] 2017-09-11 13:04
I am not sure if I understand the problem. Is it that ceph -s and Ceph Dash show a different cluster status? If yes, can you please provide a screenshot of ceph-dash and the output of `ceph status --format=json-pretty`?

**Comment by wzs803** [comment] 2017-09-11 13:18
![0911](https://user-images.githubusercontent.com/3351066/30276204-a5c72eda-9736-11e7-906e-cb394f8b9d83.png)
![0911-1](https://user-images.githubusercontent.com/3351066/30276222-b942895a-9736-11e7-9a7e-ed61a28d37a9.png)

**Comment by Crapworks** [comment] 2017-09-11 13:23
@wzs803 Thank you!

The problem is that ceph-dash does exactly what ceph tell it. Ceph-dash should show the overall status, as mentioned. Since luminous they changed a lot about how the status API works. 

I have no idea why there is now a `status` and an `overall_status` in the API or what the differences are. I mean there seems to be something wrong, but the checks are empty. I could change the field to status. but that would be more guessing that knowing. Are there any indications in the console output about what causes the HEALTH_WARN?

**Comment by wzs803** [comment] 2017-09-11 13:41
very thanks.
 I find  status and  overall_status  in ceph Official， No result was found。
I am a new problem.  python check-ceph-dash.py --url ' ' 

Traceback (most recent call last):
  File "check-ceph-dash.py", line 91, in <module>
    main()
  File "check-ceph-dash.py", line 87, in main
    print "%s|%s" % (status.get_nagios_string(), status.get_perf_data())
  File "check-ceph-dash.py", line 76, in get_nagios_string
    summary = '\n'.join([ "{severity}: {summary}".format(**problems) for problems in self['health']['summary']])
KeyError: 'summary'

**Comment by Crapworks** [comment] 2017-09-12 16:45
Hi @wzs803 

This is a check_ceph-dash issue. I've updated the code in that repository, it should work now with both version of ceph-dash. Can you please check and confirm that this is working?

And can you please show me a full screenshot of your ceph-dash, so I can check if everything looks ok for luminous? That would be pretty helpfull for me!

Cheers,
Christian

**Comment by wzs803** [comment] 2017-09-15 09:00
luminous 

ceph-dash  full screenshot。

![l](https://user-images.githubusercontent.com/3351066/30474759-4af63d94-9a37-11e7-9697-8bf5f620fcf5.png)

**Comment by Crapworks** [comment] 2017-09-15 09:12
Thanks! Is check_ceph_dash working now?

**Comment by Crapworks** [comment] 2017-10-23 17:38
going to close this one now.

**Closed by Crapworks** 2017-10-23 17:38 UTC
