### ISSUE TITLE
Ceph Dashboard pulling Graphite data but no graph

### ISSUE THREAD

**Issue by symmcom** [Crapworks/ceph-dash#15] opened 2015-06-12 22:07 UTC
Hello, 
First of all I just love your dashboard. Have been using it for a while now and it does what it is designed to do very well. 
The issue that i am having right now is, I have finalyl setup Icinga+Graphite. Icinga pulling data from Ceph which can be viewed from graphite web. I have modified config.json in your ceph dashboard but it is not showing any data under Performance metrics block. Missing something? How should the target be pointed inside the config file?
Thanks!

**Comment by Crapworks** [comment] 2015-06-13 08:49
Hi Symmcom,
without any further information, it is hard to tell where the problem is. Can you provide me your config.json? I would debug this using Firebug, which will show you any errors coming back from graphite. If it is SHOWING the section "Performance Metrics", but just no data, it is usually an issue with the targets. But again, I need some more information to help you with this.

Regards,
Christian

**Comment by symmcom** [comment] 2015-06-13 14:36
Hi Chritian, 
Thank you so much for your response. I also think it is because improper target that it is not receiving any data. Below is my config.json:
=====================================
{
    "ceph_config": "/etc/ceph/ceph.conf",
    "graphite": {
        "url": "10.1.100.1:8080",
        "metrics": [
            {
                "targets": [ 
		    "avg(monitoring.ceph-mon*.ceph_overall_cluster_status.read_bytes_sec)",
		    "avg(monitoring.ceph-mon*.ceph_overall_cluster_status.write_bytes_sec)"
                ],
                "labels": [ "Read", "Write" ],
                "from": "-2h",
                "mode": "byteRate"
            },
            {
                "targets": [ 
                    "avg(monitoring.ceph-mon*.ceph_overall_cluster_status.op_per_sec)"
                ],
                "labels": [ "IOPS" ],
                "colors": [ "#5bc0de" ],
                "from": "-2h"
            }
        ]
    }
}
================================
I also installed Grafana on my Icinga node. It pulls Ceph data just fine. I can also ceph data directly in the browser by entering this:
http://10.1.100.1:8080/render?target=icinga.node01.read_bytes_sec
In the config.json should enter like this at the end of the target?: icinga.node01.read_bytes_sec

**Comment by Crapworks** [comment] 2015-06-13 15:47
Exactly, the target parameter in the config is actually passed directly to the target paramter in the graphite url. Please tell me if that worked for you.

**Comment by symmcom** [comment] 2015-06-13 19:02
Could you please tell me which one will be correct target out of following?
1. 
"targets": [
"avg(monitoring.ceph-mon.ceph_overall_cluster_status.icinga.node01.read_bytes_sec)",
"avg(monitoring.ceph-mon.ceph_overall_cluster_status.icinga.node01.write_bytes_sec)"
],

2. 
"targets": [
"avg(icinga.node01.read_bytes_sec)",
"avg(icinga.node01.write_bytes_sec)"
],

3. 
"targets": [
"icinga.node01.read_bytes_sec)",
"icinga.node01.write_bytes_sec)"
],

**Comment by Crapworks** [comment] 2015-06-14 18:30
If you only have one node that you want to graph, then

```json
"targets": [
    "icinga.node01.read_bytes_sec",
    "icinga.node01.write_bytes_sec"
]
```

should work.

**Comment by symmcom** [comment] 2015-06-15 13:46
Unfortunately this did not work. Still no graph. i know the target is accurate because i can use the same target in a browser to see the graphs. Any ideas?

**Comment by Crapworks** [comment] 2015-06-17 13:33
Like I told you, you should check the requests with firebug, to see what is going wrong. Can you please provide me again the full ```config.json```?

**Comment by Crapworks** [comment] 2015-07-11 17:35
I guess it is working now? I am closing this :)

**Closed by Crapworks** 2015-07-11 17:35 UTC

**Comment by symmcom** [comment] 2015-07-11 22:20
Hello, 

Thanks for closing the ticket. Actually i could never get the Icinga+Ceph-dash to work to display graph. But its ok because i moved to Zabbix from Icinga. Much better option in my case. 

I do use your ceph-bash daily to monitor our ceph cluster. You have done a good job and it just works although without the graph. 
Are you planning anything for Zabbix?


Wasim Ahmed
Senior IT Consultant
 <http://www.symmcom.ca/files/logo/symm-cloud-sm.png> 
E wahmed@symmcom.com
P 1-855-796-6269
F 1-855-796-6266
W www.symmcom.com

-----Original message-----

**Comment by Crapworks** [comment] 2015-07-27 10:40
Hi,
actually the graphite integration is not bound to Nagios/Icinga or any other monitoring system. If you can see the graphs in graphite, you can also integrate them into ceph-dash. If you could send me again your config.json we can have another look at it.
